### ISSUE TITLE
Non prende OpenAI Key dal .env

### ISSUE THREAD

**Issue by spesknight** [Neggia/SEM#39]
/web/SEM/node_modules/openai/src/index.ts:109
      throw new Errors.OpenAIError(
            ^
Error: The OPENAI_API_KEY environment variable is missing or empty; either provide it, or instantiate the OpenAI client with an apiKey option, like new OpenAI({ apiKey: 'My API Key' }).
    at new OpenAI (/web/SEM/node_modules/openai/src/index.ts:109:13)
    at Object.<anonymous> (/web/SEM/src/service_openai/service_openai.service.ts:52:16)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/web/SEM/src/app.module.ts:14:1)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)

Workaround: inserire la key direttamente in ode_modules/openai/src/index.ts:105

**Comment by Neggia** [comment]
Ciao, in attesa di capire meglio perchè non prende la variabile sul tuo sistema, ti conviene modificare la riga 50 del file src\service_openai\service_openai.service.ts, non quella dentro node_modules:

apiKey: process.env.OPENAI_API_KEY, => apiKey: <sostituire con la chiave API racchiusa tra doppi apici, ad es. "abcd">
